### ISSUE TITLE
People on the roof

### ISSUE THREAD

**Issue by TherealCougar** [TheBlackParrot/blockland-falling-platforms#45]
People getting onto roof and killing players that are trying to play the mini game 
Hoogle
![hoogle](https://cloud.githubusercontent.com/assets/15132142/10499331/45be856e-7295-11e5-813f-70a7d25cef52.png)
Metario
![met 1](https://cloud.githubusercontent.com/assets/15132142/10499345/55f4c196-7295-11e5-842a-7c5d2ae3506c.png)
![met 2](https://cloud.githubusercontent.com/assets/15132142/10499348/586ae39c-7295-11e5-8162-971c345a1836.png)
![met 3](https://cloud.githubusercontent.com/assets/15132142/10499351/5afccff8-7295-11e5-9baf-7f6d95c07150.png)
Other things metarios done by cheating in the mini
![met 4](https://cloud.githubusercontent.com/assets/15132142/10499360/686f139e-7295-11e5-99a4-a8cb44aefa75.png)
![met 5](https://cloud.githubusercontent.com/assets/15132142/10499362/6a6d63bc-7295-11e5-9a5b-e1b87f17f292.png)

**Comment by TheBlackParrot** [comment]
https://github.com/TheBlackParrot/blockland-falling-platforms/issues/46
